from PyQt5 import QtCore, QtWidgets

class Properties(QtWidgets.QWidget):

    def __init__(self,parent):
        super(Properties,self).__init__(parent)
        self.initUI()

    def initUI(self):
        self.tab = QtWidgets.QTabWidget()
        #Parameters page
        self.parametersPage = QtWidgets.QWidget()
        self.parametersGrid = QtWidgets.QGridLayout(self.parametersPage)
        self.sensitivityLabel = QtWidgets.QLabel('Sensitivity (pixel/sqrt[keV])')
        self.sensitivityEdit = QtWidgets.QLineEdit('361.13')
        self.energyLabel = QtWidgets.QLabel('Electron Energy (keV)')
        self.energyEdit = QtWidgets.QLineEdit('20')
        self.azimuthLabel = QtWidgets.QLabel('Azimuth(\u00B0)')
        self.azimuthEdit = QtWidgets.QLineEdit('0')
        self.scaleBarLabel = QtWidgets.QLabel('Scale Bar Length (\u212B)')
        self.scaleBarEdit = QtWidgets.QLineEdit('5')
        self.labelButton = QtWidgets.QPushButton('Label')
        self.calibrateButton = QtWidgets.QPushButton('Calibrate')
        self.clearButton = QtWidgets.QPushButton('Clear')
        self.labelButton.setSizePolicy(QtWidgets.QSizePolicy.Fixed,QtWidgets.QSizePolicy.Fixed)
        self.calibrateButton.setSizePolicy(QtWidgets.QSizePolicy.Fixed,QtWidgets.QSizePolicy.Fixed)
        self.clearButton.setSizePolicy(QtWidgets.QSizePolicy.Fixed,QtWidgets.QSizePolicy.Fixed)
        self.buttonGrid1 = QtWidgets.QGridLayout()
        self.buttonGrid1.addWidget(self.labelButton,0,0)
        self.buttonGrid1.addWidget(self.calibrateButton,0,1)
        self.buttonGrid1.addWidget(self.clearButton,0,2)

        self.parametersGrid.addWidget(self.sensitivityLabel,0,0)
        self.parametersGrid.addWidget(self.sensitivityEdit,0,1)
        self.parametersGrid.addWidget(self.energyLabel,1,0)
        self.parametersGrid.addWidget(self.energyEdit,1,1)
        self.parametersGrid.addWidget(self.azimuthLabel,2,0)
        self.parametersGrid.addWidget(self.azimuthEdit,2,1)
        self.parametersGrid.addWidget(self.scaleBarLabel,3,0)
        self.parametersGrid.addWidget(self.scaleBarEdit,3,1)
        self.parametersGrid.addLayout(self.buttonGrid1,4,0,1,2)
        self.tab.addTab(self.parametersPage,"Parameters")

        #image adjust page
        self.imageAdjustPage = QtWidgets.QWidget()
        self.imageAdjustGrid = QtWidgets.QGridLayout(self.imageAdjustPage)
        self.brightnessLabel = QtWidgets.QLabel('Brightness ({})'.format(30))
        self.brightnessSlider= QtWidgets.QSlider(QtCore.Qt.Horizontal)
        self.brightnessSlider.setMinimum(0)
        self.brightnessSlider.setMaximum(100)
        self.brightnessSlider.setValue(30)
        self.blackLevelLabel = QtWidgets.QLabel('Black Level ({})'.format(50))
        self.blackLevelSlider= QtWidgets.QSlider(QtCore.Qt.Horizontal)
        self.blackLevelSlider.setMinimum(0)
        self.blackLevelSlider.setMaximum(500)
        self.blackLevelSlider.setValue(50)
        self.autoWBLabel = QtWidgets.QLabel('Auto white balance')
        self.autoWBCheckBox = QtWidgets.QCheckBox()

        self.applyButton2 = QtWidgets.QPushButton('Apply')
        self.resetButton2 = QtWidgets.QPushButton('Reset')
        self.applyButton2.setSizePolicy(QtWidgets.QSizePolicy.Fixed,QtWidgets.QSizePolicy.Fixed)
        self.resetButton2.setSizePolicy(QtWidgets.QSizePolicy.Fixed,QtWidgets.QSizePolicy.Fixed)
        self.buttonGrid2 = QtWidgets.QGridLayout()
        self.buttonGrid2.addWidget(self.applyButton2,0,0)
        self.buttonGrid2.addWidget(self.resetButton2,0,1)

        self.imageAdjustGrid.addWidget(self.brightnessLabel,0,0)
        self.imageAdjustGrid.addWidget(self.brightnessSlider,0,1)
        self.imageAdjustGrid.addWidget(self.blackLevelLabel,1,0)
        self.imageAdjustGrid.addWidget(self.blackLevelSlider,1,1)
        self.imageAdjustGrid.addWidget(self.autoWBLabel,2,0)
        self.imageAdjustGrid.addWidget(self.autoWBCheckBox,2,1)
        self.imageAdjustGrid.addLayout(self.buttonGrid2,3,0,1,2)
        self.tab.addTab(self.imageAdjustPage,"Image Adjust")

        #profile options page
        self.profileOptionsPage = QtWidgets.QWidget()
        self.profileOptionsGrid = QtWidgets.QGridLayout(self.profileOptionsPage)
        self.integralHalfWidthLabel = QtWidgets.QLabel('Integral Half Width ({:3.2f} \u212B\u207B\u00B9)'.format(0.4))
        self.integralHalfWidthSlider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
        self.integralHalfWidthSlider.setMinimum(0)
        self.integralHalfWidthSlider.setMaximum(100)
        self.integralHalfWidthSlider.setValue(40)
        self.chiRangeLabel = QtWidgets.QLabel('Chi Range ({}\u00B0)'.format(60))
        self.chiRangeSlider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
        self.chiRangeSlider.setMinimum(0)
        self.chiRangeSlider.setMaximum(180)
        self.chiRangeSlider.setValue(60)
        self.radiusLabel = QtWidgets.QLabel('Radius ({:3.2f} \u212B\u207B\u00B9)'.format(5.00))
        self.radiusSlider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
        self.radiusSlider.setMinimum(0)
        self.radiusSlider.setMaximum(100)
        self.radiusSlider.setValue(25)
        self.tiltAngleLabel = QtWidgets.QLabel('Tilt Angle ({:2.1f}\u00B0)'.format(0.0))
        self.tiltAngleSlider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
        self.tiltAngleSlider.setMinimum(-150)
        self.tiltAngleSlider.setMaximum(150)
        self.tiltAngleSlider.setValue(0)

        self.applyButton3 = QtWidgets.QPushButton('Apply')
        self.resetButton3= QtWidgets.QPushButton('Reset')
        self.applyButton3.setSizePolicy(QtWidgets.QSizePolicy.Fixed,QtWidgets.QSizePolicy.Fixed)
        self.resetButton3.setSizePolicy(QtWidgets.QSizePolicy.Fixed,QtWidgets.QSizePolicy.Fixed)
        self.buttonGrid3 = QtWidgets.QGridLayout()
        self.buttonGrid3.addWidget(self.applyButton3,0,0)
        self.buttonGrid3.addWidget(self.resetButton3,0,1)

        self.profileOptionsGrid.addWidget(self.integralHalfWidthLabel,0,0)
        self.profileOptionsGrid.addWidget(self.integralHalfWidthSlider,0,1)
        self.profileOptionsGrid.addWidget(self.chiRangeLabel,1,0)
        self.profileOptionsGrid.addWidget(self.chiRangeSlider,1,1)
        self.profileOptionsGrid.addWidget(self.radiusLabel,2,0)
        self.profileOptionsGrid.addWidget(self.radiusSlider,2,1)
        self.profileOptionsGrid.addWidget(self.tiltAngleLabel,3,0)
        self.profileOptionsGrid.addWidget(self.tiltAngleSlider,3,1)
        self.profileOptionsGrid.addLayout(self.buttonGrid3,4,0,1,2)
        self.tab.addTab(self.profileOptionsPage,"Profile Options")
        self.tab.setSizePolicy(QtWidgets.QSizePolicy.Expanding,QtWidgets.QSizePolicy.Fixed)

        self.UIgrid = QtWidgets.QGridLayout()
        self.UIgrid.addWidget(self.tab,0,0)
        self.UIgrid.setContentsMargins(0,0,0,0)
        self.setLayout(self.UIgrid)
        self.show()
